### PR TITLE
xcrun isn't located in Xcode folder. But in /usr/bin.

### PR DESCRIPTION
**Pull request by mikaoj**
Invoke it directly without xcode path.

### CODE REVIEW

**Comment by mikaoj** [comment]
Is there any way to test this before merge?
Not sure if xcrun can be invoked directly or if it should be appended to the path /usr/bin

**Comment by mikaoj** [comment]
Related to #9

**Comment by lszucs** [comment]
@mikaoj I'm checking your fix right now, thanks.

**Comment by lszucs** [comment]
@mikaoj many thanks for the PR, it needed some changes and it was urgent, so I fixed it separately.

**Pull request closed without merging**
